name: techten-planet
services:
  - name: backend
    source_dir: backend/
    github:
      repo: TechtenPlanet/techten-frontend
      branch: monorepo-setup
      deploy_on_push: true
    build_command: |
      npm install && \
      npm --prefix ../frontend install && \
      npm --prefix ../frontend run build && \
      rm -rf public && mkdir -p public && \
      cp -R ../frontend/build/* public/
    run_command: npm start
    http_port: 8080
    routes:
      - path: /
      - path: /api
    environment_variables:
      - key: NOTION_API_TOKEN
        scope: RUN_TIME
        value: ${NOTION_API_TOKEN}
      - key: NOTION_BLOG_DATABASE_ID
        scope: RUN_TIME
        value: ${NOTION_BLOG_DATABASE_ID}
      - key: NOTION_COURSE_DATABASE_ID
        scope: RUN_TIME
        value: ${NOTION_COURSE_DATABASE_ID}
      - key: NOTION_EVENT_DATABASE_ID
        scope: RUN_TIME
        value: ${NOTION_EVENT_DATABASE_ID}
      - key: NOTION_CONTACT_DATABASE_ID
        scope: RUN_TIME
        value: ${NOTION_CONTACT_DATABASE_ID}
      - key: NOTION_ENROLLMENT_DATABASE_ID
        scope: RUN_TIME
        value: ${NOTION_ENROLLMENT_DATABASE_ID}
      - key: NOTION_EVENT_REGISTRATION_DATABASE_ID
        scope: RUN_TIME
        value: ${NOTION_EVENT_REGISTRATION_DATABASE_ID}
      - key: NOTION_MENTOR_DATABASE_ID
        scope: RUN_TIME
        value: ${NOTION_MENTOR_DATABASE_ID}
      - key: NOTION_PARTNERSHIP_DATABASE_ID
        scope: RUN_TIME
        value: ${NOTION_PARTNERSHIP_DATABASE_ID}
      - key: NOTION_SPONSORSHIP_DATABASE_ID
        scope: RUN_TIME
        value: ${NOTION_SPONSORSHIP_DATABASE_ID}
      - key: NOTION_VOLUNTEER_DATABASE_ID
        scope: RUN_TIME
        value: ${NOTION_VOLUNTEER_DATABASE_ID}


        